import { Geist, Geist_Mono, Playfair_Display, Playfair_Display_SC } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";

export const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const playfairSc = Playfair_Display_SC({
  variable: "--font-playfair-sc",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "IOT Auto Hub",
  description: "Generated by create next app",
};
// This is the root layout for your Next.js application.
// It wraps all pages and components in your app.
// You can use it to set global styles, metadata, and other settings.
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${playfairSc.variable}`}>
      <body >
        {/* <Topbar/> */}
        <Navbar />
        {children}

      </body>
    </html>
  );
}